// 36+ Realistic Seed Products across Skincare, Makeup, Hair, Body
export const seedProducts = [
  // 1. Skincare - Moisturizer
  {
    name: "HydraGel Ultra-Light Moisturizer",
    brand: "Joyory Labs",
    category: "Skincare",
    subcategory: "Moisturizer",
    price: 649,
    mrp: 799,
    discount: 19,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1608248597359-009d115e8557?w=600&auto=format&fit=crop&q=80"
    ],
    description: "An oil-free, weightless water-burst gel moisturizer formulated for oily and combination skin. Delivers 48-hour hydration with zero greasy residue.",
    shortDescription: "Ultra-lightweight oil-free water gel with 2% Hyaluronic Acid and Centella.",
    ingredients: ["2% Hyaluronic Acid", "Niacinamide", "Centella Asiatica", "Green Tea Extract"],
    benefits: ["Controls shine all day", "Strengthens moisture barrier", "Cools inflamed skin"],
    howToUse: "Apply a coin-sized amount onto cleansed skin morning and night.",
    texture: "Water Gel",
    finish: "Matte",
    skinTypes: ["Oily", "Combination", "Acne-prone"],
    concerns: ["Excess Oil", "Dehydration", "Redness"],
    tags: ["lightweight", "moisturizer", "oil-control", "gel", "matte"],
    rating: 4.8,
    reviewCount: 384,
    stock: 45,
    sku: "JOY-SKN-001",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    reviewSummary: {
      positiveThemes: ["Ultra lightweight texture", "Instant absorption", "Non-comedogenic", "Controls shine all day"],
      concerns: ["Jar packaging could use a spatula"],
      sentimentScore: 0.94,
      sentimentLabel: "Overwhelmingly Positive"
    }
  },
  // 2. Skincare - Cleanser
  {
    name: "Oat & Cica Calming Foaming Cleanser",
    brand: "Minimalist",
    category: "Skincare",
    subcategory: "Face Wash",
    price: 349,
    mrp: 399,
    discount: 13,
    images: [
      "https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Ultra-gentle sulfate-free foaming face wash with colloidal oat and soothing cica extract. Removes excess sebum and impurities without stripping the acid mantle.",
    shortDescription: "Sulfate-free oat and cica wash for sensitive and acne-prone skin.",
    ingredients: ["Colloidal Oat", "Centella Asiatica", "Panthenol (Vitamin B5)", "Glycerin"],
    benefits: ["Non-stripping clean", "Calms reactive redness", "pH balanced 5.5"],
    howToUse: "Lather a small pump with water, massage over face for 60 seconds and rinse with lukewarm water.",
    texture: "Gentle Foam",
    finish: "Soft & Supple",
    skinTypes: ["Sensitive", "Combination", "Oily", "Normal"],
    concerns: ["Redness", "Barrier Damage", "Clogged Pores"],
    tags: ["cleanser", "oat", "cica", "sensitive", "face wash"],
    rating: 4.7,
    reviewCount: 420,
    stock: 60,
    sku: "MIN-CLN-002",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 3. Skincare - Serum
  {
    name: "Niacinamide 10% + Zinc 1% Oil Control Serum",
    brand: "Minimalist",
    category: "Skincare",
    subcategory: "Serum",
    price: 599,
    mrp: 699,
    discount: 14,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80"
    ],
    description: "High-potency clinical serum with pure pharmaceutical-grade Niacinamide and Zinc PCA to visibly reduce sebum production, pore appearance, and post-acne dark marks.",
    shortDescription: "10% Niacinamide + 1% Zinc PCA serum for blemish control and dark spots.",
    ingredients: ["10% Niacinamide", "1% Zinc PCA", "EUK-134 Antioxidant", "Aloe Leaf Juice"],
    benefits: ["Minimizes enlarged pores", "Evens skin tone", "Balances oil production"],
    howToUse: "Apply 2-3 drops after cleansing and toning before heavier creams.",
    texture: "Lightweight Liquid",
    finish: "Quick Dry Natural",
    skinTypes: ["Oily", "Blemish-prone", "Combination"],
    concerns: ["Dark Spots", "Pore Size", "Excess Sebum"],
    tags: ["serum", "niacinamide", "zinc", "pores", "brightening"],
    rating: 4.9,
    reviewCount: 890,
    stock: 80,
    sku: "MIN-SER-003",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 4. Skincare - Sunscreen
  {
    name: "Watermelon Cooling Glow Sunscreen SPF 50+ PA++++",
    brand: "Dot & Key",
    category: "Skincare",
    subcategory: "Sunscreen",
    price: 495,
    mrp: 595,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Ultra-refreshing, non-sticky sunscreen formulated with watermelon extract, hyaluronic acid, and broad-spectrum UV filters. Absorbs in 10 seconds with zero white cast.",
    shortDescription: "Zero-white cast hydrating cooling sunscreen with SPF 50+ PA++++.",
    ingredients: ["Watermelon Extract", "Hyaluronic Acid", "Tinosorb M", "Uvinul A Plus"],
    benefits: ["Zero white cast", "Instant cooling sensation", "Broad-spectrum UVA/UVB shield"],
    howToUse: "Apply two finger lengths generously to face and neck 15 minutes before sun exposure.",
    texture: "Fluid Gel",
    finish: "Natural Dewy Glow",
    skinTypes: ["All Skin Types", "Combination", "Dry"],
    concerns: ["Sun Damage", "Tan Prevention", "Dullness"],
    tags: ["sunscreen", "spf50", "cooling", "watermelon", "no white cast"],
    rating: 4.8,
    reviewCount: 650,
    stock: 55,
    sku: "DOT-SUN-004",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 5. Skincare - Toner
  {
    name: "Green Tea Alcohol-Free Clarifying Toner",
    brand: "Plum",
    category: "Skincare",
    subcategory: "Toner",
    price: 390,
    mrp: 450,
    discount: 13,
    images: [
      "https://images.unsplash.com/photo-1617897903246-719242758050?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Gentle, non-drying toner packed with antioxidant-rich green tea leaf water and glycolic acid to sweep away dead skin cells and prevent breakout congestion.",
    shortDescription: "Alcohol-free green tea toner with glycolic acid for clear, balanced skin.",
    ingredients: ["Green Tea Leaf Extract", "Glycolic Acid", "Glycerin", "Organic Aloe Juice"],
    benefits: ["Shrinks appearance of pores", "Prevents fresh breakouts", "100% alcohol free"],
    howToUse: "Pour onto a cotton pad or palms and gently press into cleansed face.",
    texture: "Watery Fluid",
    finish: "Hydrated Fresh",
    skinTypes: ["Oily", "Acne-prone", "Combination"],
    concerns: ["Breakouts", "Pore Congestion", "Uneven Texture"],
    tags: ["toner", "green tea", "alcohol-free", "acne", "pores"],
    rating: 4.6,
    reviewCount: 310,
    stock: 35,
    sku: "PLM-TNR-005",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false
  },
  // 6. Skincare - Face Mask
  {
    name: "Matcha Mud Detox Pore Purifying Mask",
    brand: "Pilgrim",
    category: "Skincare",
    subcategory: "Face Mask",
    price: 525,
    mrp: 650,
    discount: 19,
    images: [
      "https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Deep-cleaning clay mask with ceremonial Japanese matcha and white kaolin clay. Draws out blackheads, pollutants, and excess oil without cracking the skin.",
    shortDescription: "Detoxifying green matcha clay mask for smooth, purified pores.",
    ingredients: ["Japanese Matcha Tea", "Kaolin Clay", "Bentonite", "Sweet Almond Oil"],
    benefits: ["Clears blackheads", "Soothes skin fatigue", "Does not overdrying"],
    howToUse: "Apply even layer over face, leave for 10-12 minutes, rinse with warm water.",
    texture: "Creamy Mud",
    finish: "Soft Matte",
    skinTypes: ["Oily", "Combination", "Normal"],
    concerns: ["Blackheads", "Dullness", "Excess Sebum"],
    tags: ["mask", "clay", "matcha", "detox", "pores"],
    rating: 4.5,
    reviewCount: 195,
    stock: 28,
    sku: "PLG-MSK-006",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true
  },
  // 7. Skincare - Night Cream
  {
    name: "Ceramide & Peptide Barrier Night Recovery Cream",
    brand: "Joyory Labs",
    category: "Skincare",
    subcategory: "Night Cream",
    price: 849,
    mrp: 999,
    discount: 15,
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Intense overnight restorative barrier cream with 5 essential ceramides and multi-peptides to seal moisture and reverse transepidermal water loss while you sleep.",
    shortDescription: "5-Ceramide + Multi-Peptide overnight barrier repair cream.",
    ingredients: ["5 Essential Ceramides", "Copper Peptides", "Squalane", "Oat Kernel Extract"],
    benefits: ["Restores damaged moisture barrier", "Locks in active serums", "Zero greasy pillow transfer"],
    howToUse: "Warm a pea-sized amount between fingers and press onto face as the last step of night routine.",
    texture: "Velvet Cream",
    finish: "Plump & Nourished",
    skinTypes: ["Dry", "Sensitive", "Barrier Damaged"],
    concerns: ["Dryness", "Flakiness", "Compromised Barrier"],
    tags: ["night cream", "ceramide", "peptides", "barrier", "rich"],
    rating: 4.9,
    reviewCount: 410,
    stock: 40,
    sku: "JOY-NGT-007",
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true
  },
  // 8. Skincare - Sunscreen
  {
    name: "Radiance+ Dewy Sunscreen SPF 50+ PA+++",
    brand: "Aqualogica",
    category: "Skincare",
    subcategory: "Sunscreen",
    price: 449,
    mrp: 549,
    discount: 18,
    images: [
      "https://images.unsplash.com/photo-1608248597359-009d115e8557?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Water-light sunscreen infused with watermelon and niacinamide to hydrate skin while defending against UVA/UVB rays and blue light damage.",
    shortDescription: "Hydrating water-light sunscreen for luminous dewy protection.",
    ingredients: ["Watermelon Extract", "Niacinamide", "Hyaluronic Acid", "Titanium Dioxide"],
    benefits: ["Blue light protection", "Dewy finish without oiliness", "Ultra lightweight"],
    howToUse: "Apply liberally on face and neck 15 minutes before outdoor exposure.",
    texture: "Watery Lotion",
    finish: "Luminous Dewy",
    skinTypes: ["Combination", "Dry", "Normal"],
    concerns: ["Sun Protection", "Blue Light", "Uneven Tone"],
    tags: ["sunscreen", "aqualogica", "dewy", "spf50", "lightweight"],
    rating: 4.7,
    reviewCount: 520,
    stock: 50,
    sku: "AQU-SUN-008",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 9. Makeup - Foundation
  {
    name: "Fit Me Matte + Poreless Liquid Foundation",
    brand: "Maybelline",
    category: "Makeup",
    subcategory: "Foundation",
    price: 549,
    mrp: 649,
    discount: 15,
    images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Iconic oil-free liquid foundation with micro-powders that control shine and blur pores for a natural, seamless seamless matte finish.",
    shortDescription: "Breathable liquid foundation for a natural seamless poreless matte finish.",
    ingredients: ["Micro-Powders", "Glycerin", "Dimethicone", "Iron Oxides"],
    benefits: ["16-hour shine control", "Natural pore-blurring finish", "Matches Indian skin tones"],
    howToUse: "Dot foundation onto cheeks, forehead, chin, and blend outward using a damp sponge.",
    texture: "Liquid",
    finish: "Natural Matte",
    skinTypes: ["Oily", "Combination", "Normal"],
    concerns: ["Uneven Tone", "Visible Pores", "Midday Shine"],
    tags: ["foundation", "maybelline", "matte", "fit me", "coverage"],
    rating: 4.8,
    reviewCount: 1420,
    stock: 75,
    sku: "MAY-FND-009",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 10. Makeup - Concealer
  {
    name: "Liquid Full Coverage Spot Concealer",
    brand: "Swiss Beauty",
    category: "Makeup",
    subcategory: "Concealer",
    price: 249,
    mrp: 299,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Crease-resistant, lightweight liquid concealer that provides full coverage for dark circles, blemishes, and hyperpigmentation with an effortless blend.",
    shortDescription: "High-pigment crease-proof concealer for dark circles and spots.",
    ingredients: ["Hyaluronic Acid", "Vitamin E", "Mineral Pigments", "Jojoba Esters"],
    benefits: ["Zero creasing into fine lines", "High pigmentation", "Budget friendly hero"],
    howToUse: "Dab small dots onto undereyes and blemishes, blend with fingertips or a small brush.",
    texture: "Creamy Liquid",
    finish: "Satin Matte",
    skinTypes: ["All Skin Types"],
    concerns: ["Dark Circles", "Acne Spots", "Redness"],
    tags: ["concealer", "coverage", "swiss beauty", "undereye", "budget"],
    rating: 4.7,
    reviewCount: 980,
    stock: 90,
    sku: "SWI-CNC-010",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 11. Makeup - Lipstick
  {
    name: "Forever Matte Transferproof Liquid Lipstick",
    brand: "Lakmé",
    category: "Makeup",
    subcategory: "Lipstick",
    price: 349,
    mrp: 399,
    discount: 13,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Intensely pigmented liquid lipstick with an ultra-lightweight formula that delivers rich, 16-hour smudge-proof matte color without drying out lips.",
    shortDescription: "16-hour transferproof matte liquid lipstick in versatile nude and berry shades.",
    ingredients: ["Isododecane", "Vitamin E", "Dimethicone", "High-Def Color Pigments"],
    benefits: ["Zero feathering", "Intense one-swipe payoff", "Featherlight comfort"],
    howToUse: "Glide wand onto clean, dry lips starting from Cupid's bow outward.",
    texture: "Silky Liquid to Matte",
    finish: "Transferproof Matte",
    skinTypes: ["All"],
    concerns: ["Lip Color Longevity", "Transfer"],
    tags: ["lipstick", "matte", "lakme", "transferproof", "longlasting"],
    rating: 4.6,
    reviewCount: 760,
    stock: 65,
    sku: "LAK-LIP-011",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 12. Makeup - Lip Gloss
  {
    name: "Hydra Glass Non-Sticky Lip Gloss",
    brand: "Swiss Beauty",
    category: "Makeup",
    subcategory: "Lip Gloss",
    price: 229,
    mrp: 299,
    discount: 23,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80"
    ],
    description: "High-shine plumping lip lacquer infused with vitamin E and jojoba oil. Delivers a reflective mirror finish with zero gummy or hair-sticking stickiness.",
    shortDescription: "High-shine mirror glass lip gloss with non-sticky hydrating formula.",
    ingredients: ["Vitamin E", "Jojoba Seed Oil", "Peptide Volumizers", "Polybutene"],
    benefits: ["High mirror shine", "Deeply moisturizing", "Plumps dry lip lines"],
    howToUse: "Wear alone for natural glassy sheen or layer over your favorite lipstick.",
    texture: "High Shine Glaze",
    finish: "Glass Shine",
    skinTypes: ["All"],
    concerns: ["Dry Lips", "Dull Lip Look"],
    tags: ["lip gloss", "glass lips", "non-sticky", "shine", "swiss beauty"],
    rating: 4.8,
    reviewCount: 340,
    stock: 50,
    sku: "SWI-GLS-012",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true
  },
  // 13. Makeup - Lip Balm
  {
    name: "Ceramide Hydrating Tinted Lip Balm SPF 30",
    brand: "Dot & Key",
    category: "Makeup",
    subcategory: "Lip Balm",
    price: 295,
    mrp: 350,
    discount: 16,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Nourishing tinted butter balm with barrier-repairing ceramides, shea butter, and SPF 30 sun protection for soft, juicy, protected lips.",
    shortDescription: "SPF 30 Ceramide tinted lip butter for sun-protected, hydrated lips.",
    ingredients: ["Ceramides NP", "Shea Butter", "SPF 30 UV Filters", "Vitamin C"],
    benefits: ["Sun defense SPF 30", "Subtle rosy tint", "Repairs chapped lips"],
    howToUse: "Swipe liberally across lips throughout the day as needed.",
    texture: "Rich Balm",
    finish: "Soft Glossy Tint",
    skinTypes: ["All"],
    concerns: ["Chapped Lips", "Sun Damage"],
    tags: ["lip balm", "spf30", "ceramide", "tinted", "dot and key"],
    rating: 4.9,
    reviewCount: 520,
    stock: 70,
    sku: "DOT-BLM-013",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 14. Makeup - Blush
  {
    name: "Velvet Cloud Soft Cheek & Lip Tint",
    brand: "Plum",
    category: "Makeup",
    subcategory: "Blush",
    price: 425,
    mrp: 495,
    discount: 14,
    images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Melt-in cream-to-powder blush tint formulated with squalane and jojoba oil. Imparts a soft-focus watercolor flush that lasts up to 10 hours.",
    shortDescription: "Multi-use cream-to-powder blush and lip flush with squalane.",
    ingredients: ["Plant Squalane", "Jojoba Oil", "Natural Mica", "Vitamin E"],
    benefits: ["Blends seamlessly with fingers", "Buildable watercolor pigment", "Does not lift foundation"],
    howToUse: "Dab a small drop onto cheekbones and blend gently upwards with fingers or sponge.",
    texture: "Whipped Mousse",
    finish: "Soft Satin Glow",
    skinTypes: ["All Skin Types"],
    concerns: ["Dull Complexion", "Flat Makeup"],
    tags: ["blush", "tint", "plum", "cheek", "natural flush"],
    rating: 4.7,
    reviewCount: 290,
    stock: 40,
    sku: "PLM-BLS-014",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true
  },
  // 15. Makeup - Mascara
  {
    name: "Lash Sensational Sky High Waterproof Mascara",
    brand: "Maybelline",
    category: "Makeup",
    subcategory: "Mascara",
    price: 699,
    mrp: 799,
    discount: 13,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Breakthrough Flex Tower brush reaches every lash from root to tip. Infused with bamboo extract and fibers for boundless length and weightless full volume.",
    shortDescription: "Sky-high waterproof lengthening mascara with bamboo extract.",
    ingredients: ["Bamboo Extract", "Lash-Extending Fibers", "Carnauba Wax", "Beeswax"],
    benefits: ["All-day waterproof wear", "No clumps or flaking", "Sky high lash length"],
    howToUse: "Wiggle brush from base of lashes outward to tips, layer for intense drama.",
    texture: "Flexible Wax Gel",
    finish: "Intense Black",
    skinTypes: ["All"],
    concerns: ["Short Lashes", "Mascara Smudging"],
    tags: ["mascara", "maybelline", "sky high", "waterproof", "lashes"],
    rating: 4.9,
    reviewCount: 1650,
    stock: 85,
    sku: "MAY-MSC-015",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 16. Makeup - Powder
  {
    name: "9to5 Flawless Matte Oil-Control Compact",
    brand: "Lakmé",
    category: "Makeup",
    subcategory: "Compact",
    price: 375,
    mrp: 450,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Silky micro-fine pressed compact powder with oil-absorbing minerals and SPF 20. Sets foundation for all-day matte freshness without looking cakey.",
    shortDescription: "Micro-fine oil control pressed powder with SPF 20.",
    ingredients: ["Talc", "Mica", "Zinc Oxide (SPF 20)", "Vitamin E"],
    benefits: ["Blocks midday shine", "Touch-up ready mirror compact", "Smooth blur effect"],
    howToUse: "Dust across T-zone and cheeks using the included velour puff or a powder brush.",
    texture: "Micro-Fine Pressed Powder",
    finish: "Velvet Matte",
    skinTypes: ["Oily", "Combination", "Normal"],
    concerns: ["Midday Shine", "Makeup Setting"],
    tags: ["compact", "powder", "matte", "lakme", "oil control"],
    rating: 4.6,
    reviewCount: 680,
    stock: 55,
    sku: "LAK-COM-016",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false
  },
  // 17. Hair - Shampoo
  {
    name: "Rosemary & Biotin Anti-Hairfall Shampoo",
    brand: "Pilgrim",
    category: "Hair",
    subcategory: "Shampoo",
    price: 495,
    mrp: 595,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Sulfate-free scalp purifying shampoo infused with Spanish Rosemary oil and Biotin to boost follicle microcirculation, strengthen weak strands, and curb breakage.",
    shortDescription: "Sulfate-free scalp strengthening shampoo with Rosemary & Biotin.",
    ingredients: ["Spanish Rosemary Oil", "Biotin", "Aloe Vera Juice", "Hydrolyzed Keratin"],
    benefits: ["Reduces hairfall from breakage", "Gentle sulfate-free cleanse", "Invigorates scalp"],
    howToUse: "Massage into wet scalp for 2 minutes to activate herbs, lather through lengths and rinse.",
    texture: "Viscous Gel",
    finish: "Clean & Voluminous",
    skinTypes: ["All Hair Types"],
    concerns: ["Hairfall", "Weak Roots", "Oily Scalp"],
    tags: ["shampoo", "hairfall", "rosemary", "biotin", "sulfate free"],
    rating: 4.8,
    reviewCount: 820,
    stock: 60,
    sku: "PLG-SHP-017",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 18. Hair - Conditioner
  {
    name: "Olive & Macadamia Mega Moisture Hair Mask & Conditioner",
    brand: "Plum",
    category: "Hair",
    subcategory: "Conditioner",
    price: 520,
    mrp: 650,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Intense deep conditioning treatment packed with cold-pressed olive oil, macadamia seed oil, and plant keratin to detangle, smooth frizz, and seal split ends.",
    shortDescription: "Rich moisturizing conditioner & mask for dry, damaged, frizzy hair.",
    ingredients: ["Olive Oil", "Macadamia Seed Oil", "Plant Keratin", "Shea Butter"],
    benefits: ["Tames humidity frizz", "Instant silky slip", "Deeply repairs heat styling damage"],
    howToUse: "Apply from mid-lengths to tips after shampooing, leave for 3-5 minutes, rinse thoroughly.",
    texture: "Rich Cream",
    finish: "Silky Soft & Glossy",
    skinTypes: ["Dry Hair", "Frizzy Hair", "Chemically Treated"],
    concerns: ["Frizz", "Split Ends", "Dryness"],
    tags: ["conditioner", "hair mask", "plum", "olive", "frizz control"],
    rating: 4.8,
    reviewCount: 540,
    stock: 45,
    sku: "PLM-CND-018",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 19. Body - Body Lotion
  {
    name: "Niacinamide + Vitamin C Brightening Body Lotion",
    brand: "Minimalist",
    category: "Body",
    subcategory: "Body Lotion",
    price: 399,
    mrp: 499,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Non-greasy, fast-absorbing daily body lotion with 3% Niacinamide and Ethyl Ascorbic Acid to even out sun tan, fade body pigmentation, and provide 24H hydration.",
    shortDescription: "3% Niacinamide + Vitamin C body lotion for even-toned, smooth skin.",
    ingredients: ["3% Niacinamide", "Vitamin C (EAA)", "Glycerin", "Shea Butter"],
    benefits: ["Fades body tan lines", "Zero greasy feeling on clothes", "Leaves skin baby soft"],
    howToUse: "Pump liberally over arms, legs, and body post-shower while skin is slightly damp.",
    texture: "Lightweight Lotion",
    finish: "Velvet Soft",
    skinTypes: ["All Skin Types"],
    concerns: ["Body Tan", "Dry Skin", "Uneven Tone"],
    tags: ["body lotion", "niacinamide", "vitamin c", "brightening", "minimalist"],
    rating: 4.9,
    reviewCount: 710,
    stock: 65,
    sku: "MIN-BDY-019",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 20. Body - Body Wash
  {
    name: "Watermelon Super Glow AHA Exfoliating Body Wash",
    brand: "Dot & Key",
    category: "Body",
    subcategory: "Body Wash",
    price: 425,
    mrp: 495,
    discount: 14,
    images: [
      "https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Luscious foaming shower gel infused with juicy watermelon extract, lactic acid, and glycolic acid to gently buff away bumpy strawberry skin and body dullness.",
    shortDescription: "AHA exfoliating body cleanser to smooth bumps and refresh skin.",
    ingredients: ["Watermelon Extract", "Lactic Acid", "Glycolic Acid", "Pro-Vitamin B5"],
    benefits: ["Smoothes rough strawberry skin", "Irresistible fresh fruit scent", "Sulfate free"],
    howToUse: "Lather onto a loofah or washcloth, gently massage over wet body and rinse.",
    texture: "Gel Foam",
    finish: "Fresh & Silky",
    skinTypes: ["All Skin Types"],
    concerns: ["Keratosis Pilaris", "Body Acne", "Dullness"],
    tags: ["body wash", "aha", "watermelon", "exfoliating", "shower gel"],
    rating: 4.7,
    reviewCount: 390,
    stock: 50,
    sku: "DOT-WSH-020",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true
  },
  // 21. Skincare - Serum
  {
    name: "2% Salicylic Acid BHA Blackhead Exfoliator",
    brand: "Minimalist",
    category: "Skincare",
    subcategory: "Serum",
    price: 549,
    mrp: 599,
    discount: 8,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Water-based leave-on liquid exfoliant with pharmaceutical-grade Salicylic Acid. Dissolves sebum plugs deep within pores to banish blackheads and active pimples.",
    shortDescription: "2% Salicylic Acid liquid for deep pore declogging and blackheads.",
    ingredients: ["2% Salicylic Acid", "Oligopeptide-10", "Aloe Vera", "Zinc PCA"],
    benefits: ["Declogs congestion", "Reduces blackheads in 2 weeks", "Non-comedogenic"],
    howToUse: "Apply 2-3 drops to clean face 2-3 nights a week.",
    texture: "Fast Penetrating Liquid",
    finish: "Clean Matte",
    skinTypes: ["Oily", "Acne-prone"],
    concerns: ["Blackheads", "Enlarged Pores", "Acne"],
    tags: ["salicylic acid", "bha", "serum", "acne", "blackheads"],
    rating: 4.8,
    reviewCount: 620,
    stock: 45,
    sku: "MIN-SER-021",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 22. Skincare - Serum
  {
    name: "10% Vitamin C + Ferulic Acid Glow Booster",
    brand: "Plum",
    category: "Skincare",
    subcategory: "Serum",
    price: 675,
    mrp: 790,
    discount: 15,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Stabilized 10% Ethyl Ascorbic Acid serum infused with Japanese Mandarin and Ferulic acid to combat free radical damage and restore lit-from-within luminosity.",
    shortDescription: "Quick-absorbing 10% Vitamin C serum for glow and dark spot reduction.",
    ingredients: ["10% Ethyl Ascorbic Acid", "Ferulic Acid", "Japanese Mandarin", "Rosehip Extract"],
    benefits: ["Fades dark spots", "Protects against pollution", "Fragrance free"],
    howToUse: "Apply 3-4 drops in the morning followed by your favorite sunscreen.",
    texture: "Watery Essence",
    finish: "Subtle Glow",
    skinTypes: ["All Skin Types", "Dull Skin"],
    concerns: ["Dullness", "Pigmentation", "Sun Spots"],
    tags: ["vitamin c", "glow", "serum", "plum", "brightening"],
    rating: 4.7,
    reviewCount: 510,
    stock: 50,
    sku: "PLM-SER-022",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 23. Skincare - Cleanser
  {
    name: "Barrier Care Hydrating Gentle Jelly Cleanser",
    brand: "Dot & Key",
    category: "Skincare",
    subcategory: "Face Wash",
    price: 395,
    mrp: 450,
    discount: 12,
    images: [
      "https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Bouncy, cushiony jelly cleanser with 5 essential ceramides and Japanese rice water that melts makeup, dirt, and excess oil while respecting natural barrier lipids.",
    shortDescription: "5-Ceramide + Rice water jelly cleanser for soft, balanced skin.",
    ingredients: ["Ceramide 1, 2, 3, 4, 6-II", "Japanese Rice Water", "Hyaluronic Acid"],
    benefits: ["No post-wash tightness", "Melts light daily makeup", "Sulfate free"],
    howToUse: "Massage gel onto damp skin for 45 seconds, rinse with water.",
    texture: "Bouncy Jelly",
    finish: "Hydrated Dewy",
    skinTypes: ["Sensitive", "Dry", "Combination"],
    concerns: ["Dryness", "Barrier Damage", "Sensitivity"],
    tags: ["cleanser", "jelly", "ceramides", "gentle", "dot and key"],
    rating: 4.8,
    reviewCount: 430,
    stock: 55,
    sku: "DOT-CLN-023",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true
  },
  // 24. Skincare - Moisturizer
  {
    name: "Clarifying BHA Pore Balance Fluid",
    brand: "PureAura",
    category: "Skincare",
    subcategory: "Moisturizer",
    price: 749,
    mrp: 899,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1608248597359-009d115e8557?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Fast-absorbing mattifying fluid with 1.5% encapsulated Salicylic Acid and Zinc PCA. Minimizes enlarged pores and balances sebum without drying.",
    shortDescription: "Lightweight fluid with BHA and Zinc for pore care and oil control.",
    ingredients: ["1.5% Salicylic Acid", "Zinc PCA", "Aloe Vera", "Allantoin"],
    benefits: ["Reduces blackheads", "No sticky film", "Great under makeup"],
    howToUse: "Apply morning and evening after serum.",
    texture: "Lightweight Fluid",
    finish: "Natural Matte",
    skinTypes: ["Oily", "Blemish-prone"],
    concerns: ["Pores", "Excess Sebum", "Acne"],
    tags: ["moisturizer", "fluid", "bha", "matte", "oil control"],
    rating: 4.7,
    reviewCount: 260,
    stock: 40,
    sku: "PUR-MST-024",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false
  },
  // 25. Skincare - Toner
  {
    name: "Rice Water 5% Niacinamide Milky Toner",
    brand: "Dot & Key",
    category: "Skincare",
    subcategory: "Toner",
    price: 445,
    mrp: 525,
    discount: 15,
    images: [
      "https://images.unsplash.com/photo-1617897903246-719242758050?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Silky milky toner packed with fermented rice bran water and 5% niacinamide to flood skin with lightweight hydration and brighten lackluster skin tone.",
    shortDescription: "Milky rice water toner with 5% Niacinamide for glass skin glow.",
    ingredients: ["Fermented Rice Water", "5% Niacinamide", "Oat Extract", "Hyaluronic Acid"],
    benefits: ["Glass skin luminous finish", "Deep hydrating bounce", "Fragrance free"],
    howToUse: "Pat 2-3 layers onto clean skin with palms.",
    texture: "Milky Emulsion",
    finish: "Hydrated Glow",
    skinTypes: ["All Skin Types", "Dull Skin"],
    concerns: ["Dullness", "Dehydration", "Uneven Texture"],
    tags: ["toner", "rice water", "niacinamide", "glass skin", "milky"],
    rating: 4.9,
    reviewCount: 470,
    stock: 50,
    sku: "DOT-TNR-025",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 26. Skincare - Sunscreen
  {
    name: "Mineral Matte 100% Zinc Physical Sunscreen SPF 50",
    brand: "Joyory Labs",
    category: "Skincare",
    subcategory: "Sunscreen",
    price: 699,
    mrp: 850,
    discount: 18,
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Pure mineral physical sunscreen with 20% micronized non-nano zinc oxide. Silky powdery finish with zero oiliness, ideal for highly reactive and acne-prone skin.",
    shortDescription: "100% Zinc Oxide mineral matte sunscreen with zero eye sting.",
    ingredients: ["20% Non-Nano Zinc Oxide", "Centella Asiatica", "Bisabolol", "Silica"],
    benefits: ["Zero chemical filters", "No eye stinging", "Instant dry touch matte"],
    howToUse: "Apply two fingers length evenly on face and neck before sunlight.",
    texture: "Velvet Mousse",
    finish: "Oil-Control Matte",
    skinTypes: ["Sensitive", "Acne-prone", "Oily"],
    concerns: ["Chemical Sensitivity", "Excess Oil", "Sun Protection"],
    tags: ["mineral sunscreen", "zinc oxide", "physical", "matte", "sensitive"],
    rating: 4.8,
    reviewCount: 320,
    stock: 45,
    sku: "JOY-SUN-026",
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true
  },
  // 27. Skincare - Face Mask
  {
    name: "Salicylic Acid 2% Instant Clarifying Sheet Mask (Pack of 5)",
    brand: "Minimalist",
    category: "Skincare",
    subcategory: "Face Mask",
    price: 499,
    mrp: 599,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Biodegradable cellulose sheet mask drenched in 2% BHA serum to quickly unclog blackheads, calm active redness, and purify congested T-zones in 15 minutes.",
    shortDescription: "Pack of 5 clarifying BHA sheet masks for immediate pore reset.",
    ingredients: ["2% Salicylic Acid", "Zinc PCA", "Tea Tree Extract", "Centella"],
    benefits: ["Immediate cooling relief", "Refines rough texture", "Pre-event skin reset"],
    howToUse: "Unfold mask, apply to face for 15-20 minutes, remove and pat remaining serum.",
    texture: "Soaked Cellulose Sheet",
    finish: "Fresh Plump",
    skinTypes: ["Oily", "Combination"],
    concerns: ["Breakouts", "Congestion"],
    tags: ["sheet mask", "salicylic acid", "clarifying", "acne", "minimalist"],
    rating: 4.6,
    reviewCount: 280,
    stock: 35,
    sku: "MIN-MSK-027",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false
  },
  // 28. Skincare - Night Cream
  {
    name: "0.3% Pure Retinol + Coenzyme Q10 Night Elixir",
    brand: "Minimalist",
    category: "Skincare",
    subcategory: "Night Cream",
    price: 599,
    mrp: 699,
    discount: 14,
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Stable, water-free retinol emulsion packaged in squalane to accelerate cell turnover, smooth early fine lines, and refine bumpy skin texture with minimal irritation.",
    shortDescription: "0.3% Pure Retinol in Squalane for cellular renewal and fine lines.",
    ingredients: ["0.3% Pure Retinol", "Coenzyme Q10", "Plant Squalane", "Tocopherol"],
    benefits: ["Boosts collagen synthesis", "Refines rough skin texture", "Minimizes fine lines"],
    howToUse: "Apply 2-3 drops at night on dry skin 2-3 times a week, followed by moisturizer.",
    texture: "Nourishing Oil-Serum",
    finish: "Soft Conditioning",
    skinTypes: ["Normal", "Dry", "Combination"],
    concerns: ["Fine Lines", "Uneven Texture", "Aging"],
    tags: ["retinol", "anti aging", "night", "squalane", "minimalist"],
    rating: 4.7,
    reviewCount: 490,
    stock: 50,
    sku: "MIN-RTN-028",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 29. Makeup - Foundation
  {
    name: "Dewy Drop Serum Foundation with SPF 30",
    brand: "Swiss Beauty",
    category: "Makeup",
    subcategory: "Foundation",
    price: 499,
    mrp: 599,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Hybrid skincare foundation packed with 2% Hyaluronic Acid and Niacinamide. Delivers featherlight medium coverage with a lit-from-within radiant glass finish.",
    shortDescription: "Skincare-infused serum foundation with SPF 30 for dewy radiant coverage.",
    ingredients: ["Hyaluronic Acid", "Niacinamide", "Vitamin E", "Mineral Pigments"],
    benefits: ["Never settles into fine lines", "Fresh breathable feel", "Hydrates all day"],
    howToUse: "Shake well, dispense 3-4 drops onto face and blend out with fingers or a brush.",
    texture: "Serum Fluid",
    finish: "Luminous Dewy",
    skinTypes: ["Dry", "Normal", "Combination"],
    concerns: ["Dullness", "Cakey Makeup"],
    tags: ["foundation", "serum foundation", "dewy", "swiss beauty", "spf30"],
    rating: 4.8,
    reviewCount: 520,
    stock: 60,
    sku: "SWI-FND-029",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true
  },
  // 30. Makeup - Lipstick
  {
    name: "Superstay Matte Ink Longwear Liquid Lipstick",
    brand: "Maybelline",
    category: "Makeup",
    subcategory: "Lipstick",
    price: 599,
    mrp: 699,
    discount: 14,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Industry benchmark transfer-proof liquid lip color that delivers flawless, saturated matte color for up to 16 hours through meals and drinks.",
    shortDescription: "Flawless 16-hour saturated transfer-proof liquid lipstick.",
    ingredients: ["Dimethicone", "Trimethylsiloxysilicate", "High-Impact Pigments"],
    benefits: ["True 16-hour wear", "Zero transfer on cups or masks", "Precision arrow applicator"],
    howToUse: "Apply in center of upper lip and follow contours, allow 2 minutes to set completely.",
    texture: "Saturated Liquid",
    finish: "Intense Matte",
    skinTypes: ["All"],
    concerns: ["Frequent Reapplication", "Smudging"],
    tags: ["lipstick", "maybelline", "superstay", "matte", "longwear"],
    rating: 4.8,
    reviewCount: 1890,
    stock: 90,
    sku: "MAY-LIP-030",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 31. Hair - Shampoo
  {
    name: "Apple Cider Vinegar Clarifying & Scalp Detox Shampoo",
    brand: "Plum",
    category: "Hair",
    subcategory: "Shampoo",
    price: 425,
    mrp: 495,
    discount: 14,
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Clarifying scalp shampoo with raw apple cider vinegar and pro-vitamin B5. Resets product buildup, balances greasy roots, and restores high natural shine.",
    shortDescription: "Clarifying ACV shampoo for scalp buildup removal and glossy strands.",
    ingredients: ["Raw Apple Cider Vinegar", "Pro-Vitamin B5", "Aloe Leaf Extract"],
    benefits: ["Dissolves hard water & styling buildup", "pH balancing", "Volumizing clean"],
    howToUse: "Use 1-2 times weekly on wet scalp, lather and rinse thoroughly.",
    texture: "Clear Fluid Gel",
    finish: "Weightless Bounce",
    skinTypes: ["Oily Scalp", "All Hair Types"],
    concerns: ["Scalp Buildup", "Limp Hair", "Dandruff"],
    tags: ["shampoo", "apple cider vinegar", "clarifying", "scalp", "plum"],
    rating: 4.7,
    reviewCount: 410,
    stock: 45,
    sku: "PLM-SHP-031",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false
  },
  // 32. Hair - Serum
  {
    name: "Redensyl + Procapil Hair Growth Vitalizer Serum",
    brand: "Pilgrim",
    category: "Hair",
    subcategory: "Hair Serum",
    price: 745,
    mrp: 895,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Award-winning leave-on scalp serum with 3% Redensyl, 3% Anagain, and Procapil. Targets thinning hair parts and reactivates dormant hair follicles in 90 days.",
    shortDescription: "3% Redensyl + Anagain scalp serum for hair density and volume.",
    ingredients: ["3% Redensyl", "3% Anagain", "Procapil", "Green Tea Extract"],
    benefits: ["Clinically proven follicle stimulation", "Water-light non-greasy texture", "Noticeably thicker density"],
    howToUse: "Apply 1ml with dropper onto dry scalp along thinning parting lines every night.",
    texture: "Watery Serum",
    finish: "Non-Greasy Dry",
    skinTypes: ["All Hair Types"],
    concerns: ["Hair Thinning", "Parting Widening"],
    tags: ["hair serum", "redensyl", "hair growth", "pilgrim", "density"],
    rating: 4.9,
    reviewCount: 950,
    stock: 55,
    sku: "PLG-SRM-032",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true
  },
  // 33. Body - Body Lotion
  {
    name: "Shea Butter & Cocoa Deep Nourishing Body Butter",
    brand: "Joyory Labs",
    category: "Body",
    subcategory: "Body Lotion",
    price: 549,
    mrp: 699,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Decadent whipped body butter with raw Ghanaian shea butter, cocoa seed butter, and sweet almond oil. Banishes winter ashiness and seals moisture for 72 hours.",
    shortDescription: "Rich raw shea and cocoa butter for 72-hour winter moisture repair.",
    ingredients: ["Raw Shea Butter", "Cocoa Seed Butter", "Sweet Almond Oil", "Vitamin E"],
    benefits: ["Heals cracked elbows and knees", "72-hour moisture seal", "Warm vanilla notes"],
    howToUse: "Warm between palms and massage deeply into dry body zones.",
    texture: "Whipped Rich Butter",
    finish: "Velvety Soft",
    skinTypes: ["Dry", "Very Dry"],
    concerns: ["Extreme Dryness", "Ashy Skin"],
    tags: ["body butter", "shea butter", "deep moisture", "body care", "joyory"],
    rating: 4.9,
    reviewCount: 380,
    stock: 40,
    sku: "JOY-BDY-033",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true
  },
  // 34. Skincare - Cleanser
  {
    name: "Gentle Rice Water & Niacinamide Daily Foam Face Wash",
    brand: "Plum",
    category: "Skincare",
    subcategory: "Face Wash",
    price: 345,
    mrp: 395,
    discount: 13,
    images: [
      "https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Soft micro-bubble cleanser with ferment rice water and 2% niacinamide. Gently rinses sunscreen and grime while keeping the skin soft and radiant.",
    shortDescription: "Rice water & niacinamide foam wash for bright, hydrated cleansing.",
    ingredients: ["Rice Water Extract", "2% Niacinamide", "Vitamin B5", "Glycerin"],
    benefits: ["Gentle micro-bubble foam", "Leaves skin radiant", "Non-drying"],
    howToUse: "Pump foam onto damp face, massage for 30 seconds, rinse well.",
    texture: "Airy Foam",
    finish: "Clean Supple",
    skinTypes: ["Normal", "Dry", "Combination"],
    concerns: ["Dullness", "Daily Cleansing"],
    tags: ["face wash", "rice water", "plum", "cleanser", "brightening"],
    rating: 4.7,
    reviewCount: 390,
    stock: 65,
    sku: "PLM-CLN-034",
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false
  },
  // 35. Makeup - Concealer
  {
    name: "Fit Me Concealer with Chamomile Extract",
    brand: "Maybelline",
    category: "Makeup",
    subcategory: "Concealer",
    price: 499,
    mrp: 549,
    discount: 9,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Oil-free breathable liquid concealer that matches skin tones to deliver a more even complexion with a natural, undetectable finish.",
    shortDescription: "Natural breathable liquid concealer for effortless daily coverage.",
    ingredients: ["Chamomile Extract", "Glycerin", "Mineral Color Pigments"],
    benefits: ["Oil-free non-comedogenic", "Natural breathable coverage", "Dermatologist tested"],
    howToUse: "Dot under eyes and over imperfections, tap gently with ring finger to blend.",
    texture: "Liquid Cream",
    finish: "Natural Satin",
    skinTypes: ["All Skin Types"],
    concerns: ["Dark Circles", "Blemishes"],
    tags: ["concealer", "maybelline", "fit me", "undereye", "makeup"],
    rating: 4.7,
    reviewCount: 1120,
    stock: 70,
    sku: "MAY-CNC-035",
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false
  },
  // 36. Skincare - Moisturizer
  {
    name: "Cica Calming Soothing Gel with 90% Pure Centella",
    brand: "Joyory Labs",
    category: "Skincare",
    subcategory: "Moisturizer",
    price: 599,
    mrp: 750,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Rapid relief soothing gel loaded with 90% Centella Asiatica leaf water, panthenol, and madecassoside. Quenches irritated, inflamed, or sunburnt skin instantly.",
    shortDescription: "90% Pure Centella Asiatica calming gel for sensitized and acne-prone skin.",
    ingredients: ["90% Centella Asiatica", "Madecassoside", "Panthenol", "Allantoin"],
    benefits: ["Instant redness reduction", "Cools hot inflamed breakouts", "Zero oils or fragrance"],
    howToUse: "Smooth over clean skin as daily moisturizer or layer thicker as a calming mask.",
    texture: "Water Jelly",
    finish: "Hydrated Matte",
    skinTypes: ["Sensitive", "Acne-prone", "Oily"],
    concerns: ["Redness", "Inflammation", "Sensitivity"],
    tags: ["cica", "centella", "soothing gel", "redness", "lightweight"],
    rating: 4.9,
    reviewCount: 460,
    stock: 55,
    sku: "JOY-CIC-036",
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true
  },
  // 37. Skincare - Serum (L'Oréal Paris)
  {
    name: "Revitalift 1.5% Hyaluronic Acid Plumping Serum",
    brand: "L'Oréal Paris",
    category: "Skincare",
    subcategory: "Serum",
    price: 799,
    mrp: 999,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Intensive hydrating serum with 1.5% pure Hyaluronic Acid. Instantly plumps and hydrates skin, visibly reducing fine lines and boosting skin radiance.",
    shortDescription: "1.5% Pure Hyaluronic Acid plumping serum for deep moisture and anti-aging bounce.",
    ingredients: ["1.5% Pure Hyaluronic Acid", "Micro Hyaluronic Acid", "Glycerin", "Ascorbyl Glucoside"],
    benefits: ["Deeply plumps skin", "Instant 42% radiance boost", "Lightweight non-sticky absorption"],
    howToUse: "Apply 3-4 drops onto clean, damp face and neck morning and night.",
    texture: "Lightweight Liquid",
    finish: "Natural Dewy Glow",
    skinTypes: ["Dry", "All Skin Types", "Mature"],
    concerns: ["Dehydration", "Fine Lines", "Dullness", "Dry Skin"],
    tags: ["loreal", "serum", "hyaluronic acid", "plumping", "revitalift", "dry skin"],
    rating: 4.8,
    reviewCount: 1450,
    stock: 60,
    sku: "LOR-REV-037",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  },
  // 38. Skincare - Moisturizer (L'Oréal Paris)
  {
    name: "Hydra Genius Daily Liquid Care Moisturizer",
    brand: "L'Oréal Paris",
    category: "Skincare",
    subcategory: "Moisturizer",
    price: 699,
    mrp: 849,
    discount: 18,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Lightweight daily liquid moisturizer infused with Aloe Water and Hyaluronic Acid. Delivers 72 hours of continuous hydration specifically formulated for dry and normal skin.",
    shortDescription: "72H daily liquid care moisturizer with Aloe Water and Hyaluronic Acid for dry skin.",
    ingredients: ["Aloe Vera Water", "Hyaluronic Acid", "Dimethiconol", "Citric Acid"],
    benefits: ["72 hours instant hydration", "Fresh water-like absorption", "Locks in moisture barrier"],
    howToUse: "Use every morning and night on clean face and neck.",
    texture: "Lightweight Fluid",
    finish: "Natural Dewy",
    skinTypes: ["Dry", "Normal", "Dehydrated"],
    concerns: ["Dry Skin", "Rough Texture", "Flakiness"],
    tags: ["loreal", "moisturizer", "hydra genius", "aloe water", "dry skin"],
    rating: 4.7,
    reviewCount: 920,
    stock: 50,
    sku: "LOR-HYD-038",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false
  }
];

export const seedUsers = [
  {
    name: "Joyory Admin",
    email: "admin@joyory.com",
    password: "Admin@Joyory2026",
    role: "admin",
    phone: "+91 98765 43210"
  },
  {
    name: "Aria Chen",
    email: "aria.chen@joyory.com",
    password: "Customer@Joyory2026",
    role: "customer",
    phone: "+91 98123 45678",
    beautyPreferences: {
      skinType: "Combination",
      skinTone: "Medium Warm",
      concerns: ["Midday Shine", "Dehydration", "Mild Redness"],
      budget: "₹500 - ₹1500",
      preferredCategories: ["Skincare", "Makeup"],
      texturePreferences: ["Lightweight Gel", "Water Gel", "Serum Fluid"],
      fragranceSensitivity: "Low"
    }
  }
];

export const seedNeedGaps = [
  {
    category: "Skincare",
    title: "Mineral Matte Physical Sunscreen Under ₹500",
    severity: "Critical",
    gapScore: 94,
    monthlySearchVolume: 18400,
    catalogSkuCount: 1,
    targetPriceRange: "₹400 - ₹550",
    currentCatalogMinPrice: "₹699",
    bounceRateOnZeroResults: "78%",
    topQueries: [
      "mineral matte sunscreen zero white cast under 500",
      "pure zinc sunscreen for oily acne prone skin",
      "non greasy physical sunscreen under 600"
    ],
    customerVoiceSnippets: [
      "Chemical filters sting my eyes, but all physical sunscreens in Joyory are above ₹700.",
      "Need a matte zinc sunscreen that fits a student budget under ₹500."
    ],
    recommendationAction: "Formulate or onboard an affordable 15-20% Zinc Oxide fluid priced at ₹449-₹499."
  },
  {
    category: "Skincare",
    title: "Barrier Repair Water Gel for Humid Climates",
    severity: "High",
    gapScore: 89,
    monthlySearchVolume: 14200,
    catalogSkuCount: 2,
    targetPriceRange: "₹500 - ₹700",
    currentCatalogMinPrice: "₹849",
    bounceRateOnZeroResults: "64%",
    topQueries: [
      "lightweight ceramide gel for monsoon",
      "barrier repair without oily heaviness",
      "ceramide cream for oily acne skin"
    ],
    customerVoiceSnippets: [
      "Most ceramide creams are thick like heavy butter. My skin broke out within 2 days in humidity.",
      "Need ceramides in a genuine water burst texture."
    ],
    recommendationAction: "Expand Joyory Labs line with a 5-Ceramide Water Burst formulation priced under ₹650."
  },
  {
    category: "Hair",
    title: "Clarifying Scalp Serum for Hard Water Residue",
    severity: "High",
    gapScore: 85,
    monthlySearchVolume: 11800,
    catalogSkuCount: 1,
    targetPriceRange: "₹450 - ₹600",
    currentCatalogMinPrice: "₹745",
    bounceRateOnZeroResults: "61%",
    topQueries: [
      "hard water hair treatment serum",
      "scalp chelating solution for metro water",
      "anti mineral buildup hair treatment"
    ],
    customerVoiceSnippets: [
      "Hard water in Bangalore makes my roots sticky by day 2 even after washing.",
      "No direct scalp chelating solution currently listed on the store."
    ],
    recommendationAction: "Launch an ACV + EDTA chelation scalp detox serum target priced at ₹499."
  },
  {
    category: "Makeup",
    title: "Fragrance-Free High-Coverage Concealer for Acne Prone Skin",
    severity: "Moderate",
    gapScore: 78,
    monthlySearchVolume: 8900,
    catalogSkuCount: 3,
    targetPriceRange: "₹300 - ₹450",
    currentCatalogMinPrice: "₹249",
    bounceRateOnZeroResults: "52%",
    topQueries: [
      "non comedogenic concealer for active acne",
      "fragrance free full coverage concealer under 500",
      "concealer with salicylic acid for pimples"
    ],
    customerVoiceSnippets: [
      "Standard concealers always make my active pimples worse because of heavy fragrances and oils.",
      "Need treatment-infused concealers."
    ],
    recommendationAction: "Source treatment-infused concealers containing tea tree or salicylic acid."
  }
];
